### ISSUE TITLE
Dependency to typo3/cms-reactions not declared

### ISSUE THREAD

**Issue by akiessling** [cobwebch/external_import#320] opened 2024-04-12 17:19 UTC
The dependency to typo3/cms-reactions is missing in composer.json

I uninstalled typo3/cms-reactions and got an error due to a missing ReactionInterface as well as a buggy database table probably due to wrong sql definition resolution from TYPO3 with missing auto increment on the uid field etc.

https://github.com/cobwebch/external_import/blob/4b8a3ed45e87bba03b6b4e6610d2695bd9fa58d8/ext_tables.sql#L14

Version: 7.2.4
TYPO3: 12.4.14

**Comment by fsuter** [comment] 2024-04-12 19:57
This a duplicate of https://github.com/cobwebch/external_import/issues/298

It is related to the problem of having introduced support for reactions while maintaining compatibility with TYPO3 11, for which reactions do not exist. There's no simple way of doing this. The documentation mentions the need to install reactions (https://docs.typo3.org/p/cobweb/external_import/7.2/en-us/Installation/Index.html), although this could probably be better highlighted.

If you wish to continue the discussion, please use https://github.com/cobwebch/external_import/issues/298

**Closed by fsuter** 2024-04-12 19:57 UTC
